### PR TITLE
Kernel size improvments (fixing #2)

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
See issue #2 .

- When the automatically chosen `kernel_size` is `0`, find the first next one that is non-zero. If none exists (degenerate case of all input points being the same), throw an informative error.
- Allow the user to explicitly choose `kernel_size`.

### CODE REVIEW

**Comment by Linux-cpp-lisp** [comment]
This is also a fairly non-obvious issue -- it took me a while to track down at first, especially since the original Rodriguez and Laio paper only mentions the kernel in passing. I think it would be good to explicitly document the parameters and the algorithm used to auto-select `kernel_size` so that more casual users are aware that there's a parameter selection going on under the hood. 

If you agree, where would you want that? The example notebook? `README.md`? Add some docstrings to `Cluster`?

**Comment by cwehmeyer** [comment]
Thank you for this fix!

> If you agree, where would you want that? The example notebook? README.md? Add some docstrings to Cluster?

Docstrings would definitely be helpful.

**Comment by quantkeyvis** [comment]
Hi Dev Team,
When I use the program with large datasets (more than 90k observations) the
whole python system crashes in the middle of the clustering. I know its not
an issue of ram as we have over 1.4 TB of ram.

Could you provide me any suggestions as to why it might crash or what code
I should fix.

Thanks for your time and consideration
Keyvis Damptey

**Comment by Linux-cpp-lisp** [comment]
@quantkeyvis I'm not the dev, but I'd suggest filing an issue here in GitHub with some more details about the data you're using and the error you're getting — it's far more likely that you'll get an answer by filing an issue than by posting here in a closed pull request. (If you think this PR is relevant to your issue, you can link it in an issue by typing `#3`.)

**Comment by quantkeyvis** [comment]
Will do, thanks Alby!

**Pull request merged**
